[project]
name = "spectro-rt"
version = "0.0.0"
description = "Skeleton del proyecto espectro-rt (sin código)"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["spectro_rt"]
